const mongoose = require('mongoose')
const ObjectId = mongoose.Schema.Types.ObjectId

const api_v3_device_camera_Schema = new mongoose.Schema({
    gateway_obid : {type:ObjectId, ref: 'api_v3_device_gateway'},
    serail_number : String,
    name : String,
    protocol : Number,
    location : String,
    status : String,
    download_current : Number,
    app_version : String,
    url : String,
    ip : String,
    port : Number,
    description : String,
    groups : ObjectId,
    group_count : Number,
    employee_group : [{type:ObjectId, ref: 'api_v1_group_group'}],
    visitor_group : [{type:ObjectId, ref: 'api_v1_group_group'}],
    blacklist_group : [{type:ObjectId, ref: 'api_v1_group_group'}],
    info_update_timestring : String,
    create_at : String,
    create_ut : String,
    update_at : String,
    update_ut : String,
    config_data : {
        device_run_type : Number,
        capture_status : String,
        capture_time : Number,
        capture_size : String,
        hdd_total : Number,
        hdd_used : Number,
        mac_address : String,
        voice_broadcast : Boolean,
        fill_light : Boolean,
        welcome_tip : String,
        verify_success_tip : String,
        verify_fault_tip : String,
        show_user_info : String,
        use_show_avatar : Boolean,
        show_user_name : Boolean,
        black_list_tip : String,
        recognition_distance : Number,
        network_relay_address : String,
        language_type : Number,
        auto_reboot : Boolean,
        reboot_time : String,
    }
})

module.exports = mongoose.model('api_v3_device_camera', api_v3_device_camera_Schema)
