FROM node:12.18.4
RUN mkdir -p /var/www/backend
WORKDIR /var/www/backend
COPY package*.json /var/www/backend/
RUN npm install
RUN npm install express-graphql
COPY . /var/www/backend
CMD [ "node", "index.js" ]
EXPOSE 3000