FROM node:12.16.3
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm install
RUN npm install express-graphql
COPY . /usr/src/app
CMD [ "node", "index.js" ]
EXPOSE 3000