mutation($_id:ID!,$app_key:String!, $sign:String!, $avatar_file:String! , $name:String, $created_at:String!,$updated_at:String!,$timestamp:String!) {
  editapi_v1_person_user(timestamp:$timestamp,_id:$_id,app_key:$app_key, sign:$sign, avatar_file:$avatar_file, created_at:$created_at,name:$name,updated_at:$updated_at){
    _id
    name
    timestamp
    avatar_file
    sign
    updated_at
    app_key
    created_at
  }
}