version: "3.7"
services:
  backend:
      image: ac_backend:lastest
      deploy:
          replicas: 1
      ports:
          - '3000:3000'
      volumes:
          - /var/www/backend:/var/www/backend
      command: >

  mongodb:         
    image: mongo
    ports:  
      - "27017:27017"              
    volumes:
      - mongodb-data:/data/db
      
  web:
    image: nginx:latest
    ports:  
      - "3001:3001" 
    expose:
      - "3001"
    volumes:
      - /var/www/myapp.conf:/etc/nginx/conf.d/default.conf
      - /var/www/front-react/build:/var/www/front-react/build

volumes:
  influx-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local
  mongodb-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local