version: "3.7"
services:
    backend:
        image: ac_backend:lastest
        deploy:
            replicas: 1
        ports:
            - '3000:3000'
        volumes:
            - /var/www/backend:/var/www/backend
        command: >
