version: "3.7"
services:
    backend:
        image: idealistchanu/access:backend
        deploy:
            replicas: 1
        ports:
            - '3000:3000'
        volumes:
            - /var/www/backend:/usr/src/app
        command: >
