version: "3.7"
services:
    frontend:
        image: idealistchanu/access:frontend
        deploy:
            replicas: 1
        ports:
            - '80:80'
        volumes:
            - /var/www/frontend:/app
        command: >
