version: '3.7'

services:
  influx:
    image: influxdb
    volumes:
      - influx-data:/var/lib/influxdb
    deploy:
      replicas: 1
      #placement:
        #constraints:
          #- node.role == manager

volumes:
  influx-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local