version: "3.7"     
services:           
  mongodb:         
    image: mongo
   # environment:    
     # MONGO_INITDB_ROOT_USERNAME: admin
     # MONGO_INITDB_ROOT_PASSWORD: master
    ports:  
      - "27017:27017"              
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local
