version: "3.7"
services:
    pm2:
        image: idealistchanu/access:pm2
        deploy:
            replicas: 1
        ports:
            - '9096:9096'
        volumes:
            - ./pm2/data/.pm2:/root/.pm2
            - /var/www/docker/cloud40.json:/var/www/docker/cloud40.json
            - /var/www/docker/mqtt.js:/var/www/docker/mqtt.js
            - /var/www/docker/mqtt_load.js:/var/www/docker/mqtt_load.js
            - /var/www/docker/mqtt_function.js:/var/www/docker/mqtt_function.js
            - /var/www/docker/mqtt_interval.js:/var/www/docker/mqtt_interval.js
            - /var/www/docker/mqtt_logs.js:/var/www/docker/mqtt_logs.js
            - /var/www/docker/schema:/var/www/docker/schema
            - /var/www/backend/uploads:/var/www/docker/uploads
            - /var/www/backend/node_modules:/var/www/docker/node_modules
        command: >
          bash -c  "pm2 start /var/www/docker/mqtt.js && tail -f /dev/null"
          bash -c  "pm2 start /var/www/docker/mqtt_interval.js && tail -f /dev/null"
